# Generated by Django 4.2.1 on 2023-05-13 08:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projects_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
