# Generated by Django 4.2.1 on 2023-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_title_skills_name_remove_skills_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='logo',
        ),
        migrations.AddField(
            model_name='skills',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
