# Generated by Django 4.2.1 on 2023-05-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_skills_logo_skills_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='body',
            new_name='Message',
        ),
    ]
